# Generated by Django 4.1.3 on 2022-11-29 06:47

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cash_on_Delivey_Orders',
            new_name='CashonDeliveyOrders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_image3',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.FloatField(blank=True, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Land Mark'),
        ),
        migrations.CreateModel(
            name='ProductSubImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_image', versatileimagefield.fields.VersatileImageField(null=True, upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subcategory')),
            ],
        ),
    ]
