# Generated by Django 4.1.3 on 2022-11-30 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product_category_product_sub_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerflash',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category'),
        ),
        migrations.AddField(
            model_name='subbanners1',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category'),
        ),
        migrations.AddField(
            model_name='subbanners2',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category'),
        ),
    ]
