# Generated by Django 4.1.3 on 2022-11-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_headerflash_category_mainbanner_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
