# Generated by Django 4.1.3 on 2022-12-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.product'),
        ),
        migrations.AlterField(
            model_name='subbanners1',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.product'),
        ),
        migrations.AlterField(
            model_name='subbanners2',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.product'),
        ),
    ]
